RA-03 implemented buttons, styles, and static resources
vvaganov/RecipeApp pull request #1
Opened 2024-07-06 18:01 UTC by vvaganov

пункт 8. Окрасить StatusBar и NavigationBar в соответствии с цветом макета. В эмуляторе ни статусбара ни навигаторбара нету. Весь экран в цвете основного контейнера. Я понял что это переопределяется через темы. Но как сделать так что бы они отображались, чтобы их переопределить, я пока не разобрался.

пункт 9. Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml). - не понял что имеется ввиду.

2024-07-07 17:11 UTC, ievetrovdev commented
> В эмуляторе ни статусбара ни навигаторбара нету. 
Это не так. Они есть на всех устройствах и их можно частично кастомизировать
<img width="473" alt="Снимок экрана 2024-07-07 в 20 07 23" src="https://github.com/vvaganov/RecipeApp/assets/153023186/e18ffb54-517f-48a3-ac92-e13caa23d03a">
<img width="476" alt="Снимок экрана 2024-07-07 в 20 07 31" src="https://github.com/vvaganov/RecipeApp/assets/153023186/bf66b2c8-2b27-4c3f-bbf9-43b936a76380">

Кастомить можно через тему с попощью statusBarColor и navigationBarColor

> пункт 9. Размеры основного отступа и половины от основного отступа (в ресурсный файл dimens.xml). - не понял что имеется ввиду.

как правило есть наиболее повторяющиеся размеры в макете. например основной отступ по бокам экрана в 16dp. ну и все размеры выносятся в ресурсный файл и обращаемся к ним по ссылкам

2024-07-07 17:11 UTC, ievetrovdev requested changes

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          enableEdgeToEdge()
Давай уберем enableEdgeToEdge(), чтобы контент активити (и фрагмента) не заезжал на статусбар и навбар.

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Не обязательно для каждой стороны прописывать марджины по отдельности. Есть более универсальные атрибуты. 
android:layout_margin=""
android:layout_marginHorizontal=""
android:layout_marginVertical=""

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
Все значения не забываем выносить в ресурсы. Размеры элементов/шрифтов, цвета, строки

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="category">Category</string>
Чтобы при глобальном поиске какой-то строки кода не попадали все значения в кучу, которые включают слово category – стоит для идентификатора этой строки сделать какое-то более общее название. Например, так title_categories. Это одна из причин. И в дальнейшем этот ресурс использовать и для заголовка экрана с категориями в шапке.

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
в ресурсы

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="cornerRadius">8dp</item>
все значения

2024-07-07 17:11 UTC, ievetrovdev commented on app/src/main/res/drawable/shape_background_favourites.xml
> +<?xml version="1.0" encoding="utf-8"?>
Шейпы нам не понадобятся, как ты уже понял) Углы скругляются с помощью corner radius

2024-07-07 17:31 UTC, vvaganov commented on app/src/main/res/drawable/shape_background_favourites.xml
> +<?xml version="1.0" encoding="utf-8"?>
Но, я тоже подумал, зачем я их делал, если все равно не использую:)

2024-07-07 17:34 UTC, vvaganov commented on app/src/main/res/values/strings.xml
> +    <string name="category">Category</string>
Понял, надо конечно больше практики нейминга. Пока конечно будет не просто, все это продумывать сразу

2024-07-07 18:27 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          enableEdgeToEdge()
Убрал!

2024-07-07 18:32 UTC, vvaganov commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
Вроде все вынес в ресурсы. Кроме android:layout_weight. Пока не смог сообразить нужно ли ли?  Нейминг пока вызывает затруднения конечно.

2024-07-07 18:33 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
>          enableEdgeToEdge()
Цвет у статус и навигатор баров поменял согласно макета. Кнопки на навигатор баре, пока не смог найти как показать.

2024-07-08 12:04 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="category">Category</string>
Все в порядке, поэтому мы здесь и учимся, чтобы откладывалось)

2024-07-08 12:23 UTC, ievetrovdev requested changes

2024-07-08 12:23 UTC, ievetrovdev commented on app/src/main/res/values-ru/strings.xml
> +    <string name="favourites">Избранное</string>
Комментарий про нейминг относится и ко второму строковому ресурсу)

2024-07-08 12:23 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="bottom_padding_horizontal">10dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-07-08 12:23 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="title_category">Category</string>
Правильно ли я понимаю, что основным языком приложения будет английский? Если так задумано – то все окей.

2024-07-08 12:23 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="@dimen/bottom_indentation"
Согласно макету отступ снизу 8dp. То что ниже – это имитация навбара устройства.

2024-07-08 12:23 UTC, ievetrovdev commented on app/build.gradle.kts
> +    val fragment_version = "1.8.1"
Обрати внимание, что все остальные библиотеки расположены в toml файле. Давай и эту либу тоже поместим туда, а обращаться будем по аналогии по ссылке.

Подробнее про новый формат хранения списка библиотек рассказываю вот тут (таймкод): https://youtu.be/bL6RQ2E729o?si=GnvTzQFjblBY7UPU&t=441

2024-07-08 12:24 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется како-либо эталонный стиль. Существуют разные подходы.

Можно в названии писать цифру в конце, которая означает размер, а можно использовать такую структуру, например
<img width="694" alt="Снимок экрана 2024-07-08 в 15 24 44" src="https://github.com/vvaganov/RecipeApp/assets/153023186/cd28acb6-aadd-48b5-91d5-ab1765dd2106">

2024-07-08 12:36 UTC, vvaganov commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginBottom="@dimen/bottom_indentation"
Исправил

2024-07-08 12:42 UTC, vvaganov commented on app/src/main/res/values/strings.xml
> +    <string name="title_category">Category</string>
Не, не задумано. Просто в уроках делаем английский с переводом, ну я и здесь так же. Т.е. если основной задумать русский, то нужно делать наоборот, в коде писать по русскому а переводить на другой язык, либо вообще без перевода?

2024-07-08 14:51 UTC, vvaganov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="bottom_padding_horizontal">10dp</dimen>
у них разные заначения, это я ошибся поставил одно значение

2024-07-08 14:53 UTC, vvaganov commented on app/src/main/res/values/strings.xml
> +    <string name="title_category">Category</string>
Но, пусть будет английский основным

2024-07-08 15:04 UTC, vvaganov commented on app/build.gradle.kts
> +    val fragment_version = "1.8.1"
исправил

2024-07-08 15:10 UTC, vvaganov commented on app/src/main/res/values-ru/strings.xml
> +    <string name="favourites">Избранное</string>
исправил

2024-07-08 15:19 UTC, vvaganov commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
логику понял:)

2024-07-08 15:19 UTC, vvaganov commented on app/src/main/res/values/dimens.xml
> +    <dimen name="bottom_padding_horizontal">10dp</dimen>
Я понял, исправил:)

2024-07-09 11:25 UTC, ievetrovdev approved these changes
с комментом для исправления в след. пр

2024-07-09 11:25 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="radius_8">8dp</dimen>
Повторять одни и те же значения размеров с разными айдишниками не рекомендуется. Пусть в dimens хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

Выше у тебя прописан дубль margin_8

2024-07-09 11:32 UTC, merged