RA-13 implemented a recipe screen with a list of ingredients and cook…
vvaganov/RecipeApp pull request #11
Opened 2024-08-01 11:47 UTC by vvaganov

…ing method

При реализации NestedScrollView. в качестве основного контейнера, вложенный ConstraintLayout при получении данных динамически,  не раскрывается на экране. Показывается только часть. Прокрутка всего экрана при этом работает. Проверил. Если  в качестве основного использовать LinearLayout то все работает корректно. Ну кроме прокрутки конечно, ее нет:)
Потратил много времени на поиск решения, но к сожалению не решил.
Возможно где то шрифты еще кривые стоят, поправлю!
С реализацией разделителя тоже какое то сомнение есть, что сделал все рационально. Контекст вызывает еще затруднение в понимании.

2024-08-01 19:58 UTC, ievetrovdev requested changes

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +
лишние пустые строки. соблюдаем аккуратность

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +
.

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content">
Установим конкретную высоту для шапки (или для изображения). Ты так уже делал на предыдущих экранах

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content">
Просто ошибка невнимательности

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        initUi()
I тоже часть аббревиатуры

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        initRecycler(view)
Что за вью? Ненадо нам такое. К элементам обращаемся иначе

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val recyclerViewIngredient = view.findViewById<RecyclerView>(R.id.rvIngredients)
про findViewById забываем. в проекте с самого начала используется только ViewBinding (перепроверь в остальных местах на всякий)

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val divider =
Можно сделать его ненулябельным , доставая контекст другим способом

            val divider = MaterialDividerItemDecoration(
                requireContext(),
                MaterialDividerItemDecoration.VERTICAL
            )

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        divider?.dividerInsetStart = 12
целые числа здесь – это обычные пиксели. Значение не корректно, тк мы должны задавать независимые от плотности экрана пикселы.

Воспользоваться можно вот таким методом, передавая dp из ресурсов. Метод будет возвращать чистые пиксели для конкретного устройства.
val sizeInDp = resources.getDimensionPixelSize(R.dimen.res_name)

2024-08-01 19:58 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                    android:text="Ингридиенты" />
в ресурсы

2024-08-02 04:56 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content">
Да, я на констрейнт сразу поставил высоту, но с ней изображение не отображалось.. А вот на изображение да, не додумался поставить:(.
Исправил, все работает:)

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val divider =
ох уж этот конткест

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        val recyclerViewIngredient = view.findViewById<RecyclerView>(R.id.rvIngredients)
Забыл:). В адаптерах только остались!

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        initRecycler(view)
Исправлено

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        initUi()
исправлено

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipe.xml
> +
исправлено

2024-08-02 06:38 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipe.xml
> +
Исправлено

2024-08-02 21:38 UTC, ievetrovdev approved these changes

2024-08-02 21:38 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/IngredientsAdapter.kt
> +        val textIngredientViewTitle: TextView = view.findViewById(R.id.tvIngredientTitle)
Тоже есть способ использовать ViewBinding

2024-08-04 04:13 UTC, merged