RA-14 calculation of ingredients from the number of servings is imple…
vvaganov/RecipeApp pull request #12
Opened 2024-08-04 04:16 UTC by vvaganov

…mented

2024-08-04 18:29 UTC, ievetrovdev commented
> …mented
> 
> Иван, чет viewBinding для адаптера пока не дается. Если есть че почитать кроме оф.документации, то дай ссылку какую нибудь!

а для адаптера технология ничем не отличается. та же разметка, тот же класс с элементами

<img width="554" alt="Снимок экрана 2024-08-04 в 21 27 57" src="https://github.com/user-attachments/assets/100821cf-6861-4229-bea7-28bd86c818b0">

2024-08-04 18:30 UTC, ievetrovdev requested changes

2024-08-04 18:30 UTC, ievetrovdev commented on gradle/libs.versions.toml
> +androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databindingRuntime" }
databinding позволяет биндить данные прямо в разметку напрямую. Но мы не планируем его использовать, так как с головой хватит ViewBinding

2024-08-04 18:30 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/IngredientsAdapter.kt
> +                quantityDouble.toInt().toString()
Вообще для чисел с точкой лучше использовать BigDecimal. Он позволяет точнее сравнивать и производить вычисления. Плюс есть встроенные методы для форматирования строк. Статья про BigDecimal: https://javarush.com/groups/posts/2274-kak-ispoljhzovatjh-bigdecimal-v-java

2024-08-05 11:12 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/IngredientsAdapter.kt
> +                quantityDouble.toInt().toString()
Dicemal поизучал, попробовал разные метода округления, отбрасывания, но так и не смог решить, задачу не показывать 0 после запятой у ингридиентов с не целым количеством:(.

2024-08-06 11:20 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/IngredientsAdapter.kt
> +                quantityDouble.toInt().toString()
Попробуй адаптировать такой код

val totalQuantity = BigDecimal(ingredientCurrentCount) * BigDecimal(quantity)

val displayQuantity = totalQuantity
.setScale(1,RoundingMode.HALF_UP)
.stripTrailingZeros()
.toPlainString()

2024-08-06 11:21 UTC, ievetrovdev approved these changes
Аппрув с некоторыми комментариями

2024-08-06 11:21 UTC, ievetrovdev commented on gradle/libs.versions.toml
> +databindingRuntime = "8.5.1"
databinding убираем тут тоже

2024-08-06 11:51 UTC, merged