RA-16 Add a Favorites icon, fixed the margins
vvaganov/RecipeApp pull request #14
Opened 2024-08-09 06:20 UTC by vvaganov

Добавил боковые отступы в коде.
Сейчас только заметил, что SeekBar  у меня не на всю ширину контейнера, хотя отступов ни каких не вижу. Подскажи, где искать?
По поводу ripple-эффект, то же пока не понял, вроде добавил атрибут, а ни какого эффекта не заметил.

2024-08-10 10:46 UTC, ievetrovdev commented
> Сейчас только заметил, что SeekBar у меня не на всю ширину контейнера, хотя отступов ни каких не вижу. Подскажи, где искать?

Верно. У виджета есть вшитые во вьюху отступы, поэтому стоит задать программно элементу отступы, например, с помощью метода setPadding

2024-08-10 10:50 UTC, ievetrovdev requested changes

2024-08-10 10:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +        ingredientListLeanerLayout.setPaddingRelative(16, 0, 16, 0)
В коде у тебя паддинги для сикбара задаются методом setPadding
 
Целые числа здесь – это обычные пиксели. Значение не корректно, тк мы должны задавать независимые от плотности экрана пикселы.

Воспользоваться можно вот таким методом, передавая dp из ресурсов. Метод будет возвращать чистые пиксели для конкретного устройства.
val sizeInDp = resources.getDimensionPixelSize(R.dimen.res_name)

2024-08-10 10:50 UTC, ievetrovdev commented on app/src/main/res/drawable/ic_heart.png
Иконки экспортируем только в векторе. Чтобы всегда четко отображались на любых разрешениях с любым масштабированием.

2024-08-10 10:50 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:id="@+id/imgFavorites"
img это скорее обозначение изображения. для ImageButton более логичным будет префикс ib

2024-08-10 13:28 UTC, vvaganov commented on app/src/main/res/drawable/ic_heart.png
Сделано

2024-08-10 13:29 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:id="@+id/imgFavorites"
исправлено

2024-08-10 13:29 UTC, vvaganov commented
а что с рипл эфектом?

2024-08-11 10:02 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:id="@+id/imgFavorites"
Также у изображений отсутствует описание контента. 

ContentDescription в Android — это описание элементов интерфейса для пользователей с ограничениями зрения, использующих средства чтения с экрана, например, TalkBack. Он важен для интерактивных элементов (кнопок, ссылок), чтобы объяснить их функции. Для декоративных элементов можно установить "@null", чтобы они игнорировались средствами чтения. Отсутствие contentDescription может сделать приложение недоступным для пользователей с нарушениями зрения.

2024-08-11 10:05 UTC, ievetrovdev requested changes

2024-08-11 10:05 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:background="?attr/selectableItemBackgroundBorderless"
Есть простой набор атрибутов, чтобы ripple эффект для элемента заработал:
android:foreground = "?selectableItemBackground"
android:clickable = "true"
android:focusable = "true"

2024-08-13 11:32 UTC, ievetrovdev approved these changes

2024-08-14 04:22 UTC, merged