RA-17 adding and deleting a recipe id to favorites by clicking
vvaganov/RecipeApp pull request #15
Opened 2024-08-15 04:02 UTC by vvaganov

2024-08-16 10:03 UTC, ievetrovdev requested changes

2024-08-16 10:03 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +const val PREF_FAVORITE_KEY = "favoritesId"
Выносим в соответствующий файл с константами

2024-08-16 10:03 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +                if (!flag) {
Здесь баг с тем двойным нажатием на иконку. Нужно на каждый клик обращаться в хранилище и проверять наличие айдишника в избранном. Иначе при каждом пересоздании экрана состояние переменной флага будет сбрасываться.

2024-08-16 10:03 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="preferencesFavoritesId">PreferencesFavoritesId</string>
Не путай строковый ресурс, который нужен для локализации с текстовым идентификатором, который принято обычно хранить в константах.

2024-08-16 16:36 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +                if (!flag) {
Но, чет я не сообразил сразу то. Какое решение нашел чтоб по клику картинку менять:)

2024-08-17 02:29 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/RecipeFragment.kt
> +const val PREF_FAVORITE_KEY = "favoritesId"
Вобще забыл, что есть файл с константами:)

2024-08-18 09:31 UTC, ievetrovdev approved these changes

2024-08-20 17:24 UTC, merged