RA-18 the favorites screen and click-through to the recipe are implem…
vvaganov/RecipeApp pull request #16
Opened 2024-08-20 18:00 UTC by vvaganov

…ented

2024-08-21 12:21 UTC, ievetrovdev requested changes

2024-08-21 12:21 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="favorite_list_title">Избранное</string>
Дубль ресурса

2024-08-21 12:21 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:text="Вы пока не добавили ни одного рецепта в избрнное" />
Для этого текста уже есть вынесенная строка

2024-08-21 12:21 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Title"
Это разве похожий на макет стиль? И позиционирование. Предлагаю привести все в порядок.

2024-08-21 16:33 UTC, vvaganov commented on app/src/main/res/layout/fragment_favorites.xml
> +        android:textAppearance="@style/TextAppearance.AppCompat.Title"
А, не заметил нижний макет! Еще подумал, мне самому что ли придумывать как это будет выглядеть:). Ну и придумал

2024-08-21 16:33 UTC, vvaganov commented on app/src/main/res/layout/fragment_favorites.xml
> +        tools:text="Вы пока не добавили ни одного рецепта в избрнное" />
исправил

2024-08-21 16:33 UTC, vvaganov commented on app/src/main/res/values/strings.xml
> +    <string name="favorite_list_title">Избранное</string>
исправил

2024-08-22 15:48 UTC, ievetrovdev approved these changes
Все ок

Иконка приложения все еще не установлена (не отображается при запуске на сплеш скрине). Используй инструкцию из ТЗ "1. Использование функции 'New Image Asset'" для корректного добавления растрового изображения https://androidsprint.ru/courses/recipeapp/learn/1.2

2024-08-24 09:55 UTC, merged