RA-20 create file viewModel for recipe
vvaganov/RecipeApp pull request #18
Opened 2024-09-02 16:36 UTC by vvaganov

Иван, привет!
Не уверен, что пока правильно понимаю суть состояния. Не совсем уверен, что там нужны строки которые не меняются динамически. 

val ingredientsTitle: Int = R.string.title_ingredient,
val servingTitle: Int = R.string.title_portions,
val cookingMethod: Int = R.string.cooking_method,

Наверное из нужно убрать. Так и не смог сообразить, нужно ли что то делать с SeekBar ом, ведь на его состояние в коде мы ни как не влияем. 
В общем пока так:)

2024-09-03 17:50 UTC, ievetrovdev commented
Не хватает третьего -  model слоя. Там лежит только бизнес-логика нашего приложения, которую можно использовать в других проектов без изменений, например в чат-боте. В них не должно быть android-зависимостей и обработки внешних данных. В нашем случае это только классы ингредиентов, категорий, рецептов

2024-09-03 18:10 UTC, ievetrovdev requested changes

2024-09-03 18:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +data class RecipeUiState(
Лучше сделать его вложенным классом во ViewModel, без её контекста он использоваться не будет

2024-09-03 18:10 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val servingTitle: Int = R.string.title_portions,
В стейте мы храним не части UI-интерфейса, а изменяющиеся данные в процессе взаимодействия пользователя с  экраном. По этим измененным данным и будет отрисовываться UI-интерфейс. Неизменяемые данные, как надпись "Ингридиенты", хранить не надо. 
Сейчас у нас меняется:
Картинка рецепта, название, ингридиенты, способ приготовления ( всё это лежит в рецептах, по отдельности хранить не надо), количество порций, в избранном ли рецепт.
По этим данным мы и будем ставить состояние кнопки Избранного, картинку рецепта и т.д. И соотвественно при взаимодействии пользователя с ui элементами, менять и сам state

Глянь пример из андроид доки, должно стать понятнее
https://developer.android.com/topic/libraries/architecture/viewmodel#implement-viewmodel

2024-09-05 09:50 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val servingTitle: Int = R.string.title_portions,
Беда у меня с андроид доками в том что английский плохо знаю(в процессе изучения), а перевод иногда такой кривой, что смысл понять трудно:(.
Со стейтом вроде как разобрался, что храним, что не храним!

Со слоем model и data вроде тоже логику понял! Думаю, будет понятней, когда данные будем получать из интернета!

2024-09-05 17:28 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val servingTitle: Int = R.string.title_portions,
Гугл потихоньку переводит свою документацию на русский, справа вверху можно выбрать другой язык.
Продублирую на русскую доку ссылку
https://developer.android.com/topic/libraries/architecture/viewmodel?hl=ru#implement-viewmodel

2024-09-05 17:31 UTC, ievetrovdev approved these changes
Молодец, все недочёты поправил. Ставлю апрув. Единственное замечание, numberServing в стейте лучше сделать Int, с числом работать удобнее в разы) Поправь в следующем ПР.
Дальше уже будем менять стейт, думаю все непонятности уйдут

2024-09-06 07:46 UTC, merged