RA-21  liveData for RecipeFragment
vvaganov/RecipeApp pull request #19
Opened 2024-09-09 09:56 UTC by vvaganov

Тема далась не сложно!
Единственное что пока не доходит, механизм работы Делегирования!

2024-09-09 17:55 UTC, ievetrovdev commented
> Тема далась не сложно! Единственное что пока не доходит, механизм работы Делегирования!

Делегат - это синтаксический сахар в первую очередь. Лучше всего поможет разобраться в его работе, попробовать реализовать тоже самое без его использования. В Джаве нету ключевого слова by. На Котлине это выглядит так:
```
class MyFragment : Fragment() {
    private lateinit var viewModel: MyViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel = ViewModelProvider(this).get(MyViewModel::class.java)
    }
  }
 ```
Можно глянуть что из себя представляет метод get у ViewModelProvider. По сути мы просто в ViewModelProvider, который содержит в себе все ViewModel, находим по ключу нашу ViewModel. Если её не существует, создаем новую и кладем во ViewModelProvider. Но в этой реализации мы должны присваивать значение внутри метода onCreate, а делегат использует lazy и создаст экземпляр при первом обращении к нему

2024-09-09 18:13 UTC, ievetrovdev requested changes

2024-09-09 18:13 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    private val mutableSelectedRecipe = MutableLiveData<RecipeUiState?>()
Давай сразу создавать пустой объект стейта при инициализации LiveData. Это нам пригодится, чтобы в дальнейшем использовать метод копирования дата класса для его изменения. Тип при этом в <> указывать уже не обязательно.
private val _recipeState = MutableLiveData(RecipeState())
Также по правилу нейминга рекомендуется называть одинаково приватную и открытую LiveData, только у приватной _recipeState в начале. Лучше указать в названии про state, поскольку она содержит экземпляр стейта

2024-09-09 18:13 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        var isFavorites: Boolean = false,
То что ты копируешь RecipeUiState с измененным значением - правильно. Создается новый экземпляр класса, но с другими значениями. var здесь не нужен, мы не изменяем текущий элемент, а инициализируем новый, просто меняя isFavorites

2024-09-09 18:13 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val selectedRecipe: MutableLiveData<RecipeUiState?> get() = mutableSelectedRecipe
Щас теряется смысл в этой переменной, поскольку она тоже Mutable. Её бы сделать обычной LiveData, чтобы фрагмент мог только смотреть на значения, а не менять их, нарушается принцип инкапсуляции

2024-09-09 18:13 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        viewModel.selectedRecipe.observe(viewLifecycleOwner, recipeObserver)
Так работает, но всё же это не стиль Котлина, много лишних строк. 
Достаточно сразу передавать в параметр функции лямбда-выражение
viewModel.selectedRecipe.observe(viewLifecycleOwner){ it ->
Log.i("!!!", "observerWork-${it?.isFavorites}")
}

2024-09-11 15:37 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        viewModel.selectedRecipe.observe(viewLifecycleOwner, recipeObserver)
Я сперва так и сделал, но увидел в андроид доках реализацию через переменную, ну и так же сделал:)

2024-09-11 15:39 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +    val selectedRecipe: MutableLiveData<RecipeUiState?> get() = mutableSelectedRecipe
Понял, потихоньку доходит

2024-09-12 21:15 UTC, ievetrovdev approved these changes

2024-09-14 04:13 UTC, merged