Ra 04 first fragment
vvaganov/RecipeApp pull request #2
Opened 2024-07-09 11:53 UTC by vvaganov

2024-07-09 12:50 UTC, ievetrovdev commented
При аппруве был уговор пофиксить коммент) 

<img width="1052" alt="Снимок экрана 2024-07-09 в 15 49 49" src="https://github.com/vvaganov/RecipeApp/assets/153023186/63d9802e-90e6-4579-bb1e-dd2c01e1cc75">

2024-07-09 12:51 UTC, ievetrovdev commented
Обращаю внимание на нейминг пулл реквеста, а именно на стиль именования.

2024-07-09 12:58 UTC, ievetrovdev requested changes
Не наблюдаю выполненного пункта 1 задания. Про fragment-ktx

2024-07-09 12:58 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            .add(R.id.mainContainer, CategoriesListFragment())
Ты используешь Java метод add/replace из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt.

Именно для импорта метода add() нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-07-09 18:50 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            .add(R.id.mainContainer, CategoriesListFragment())
Теперь я понял, что значит фраза "c комментом для исправления в следующем пр":))). Сразу вообще не дошло:).
Логику распонял.:(
[https://private-user-images.githubusercontent.com/153023186/346560437-cd28acb6-aadd-48b5-91d5-ab1765dd2106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NTA2NTEsIm5iZiI6MTcyMDU1MDM1MSwicGF0aCI6Ii8xNTMwMjMxODYvMzQ2NTYwNDM3LWNkMjhhY2I2LWFhZGQtNDhiNS05MWQ1LWFiMTc2NWRkMjEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOVQxODM5MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmNiNjUzNzQ4NjljYTQwZjMwMDQ0ZTE3NTRlNzJmODg1YTk4NWE0MzljNjIxYzM0NmVjZmZhZWYxMjQ2NzFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uEuRekY9bmzsWQ0a3K-BUq767zav-8Q_MaVbQuHvuig](url)
На скрине как пример разные свойства с разными айдишниками но одинаковым значением. Или я чего то не до понимаю. К примеру если мне нужно использовать один размер для маржина и радиуса, то какой нужно писать id?

2024-07-09 19:00 UTC, vvaganov commented
> Не наблюдаю выполненного пункта 1 задания. Про фрагмент-ktx

Ktx реализован был в 1 коммите 04 ветки, потом я делал мерж мастера, потом еще один коммит в 04 ветку.

2024-07-09 19:03 UTC, vvaganov commented
Теперь я понял, что означает фраза "c комментом для исправления в предыдущем пр":))). Сразу вообще не дошло:).
<img width="694" alt="346560437-cd28acb6-aadd-48b5-91d5-ab1765dd2106" src="https://github.com/vvaganov/RecipeApp/assets/170010881/430fb731-dc4c-45ee-a7e1-2079d71d546d">

На скрине как разные свойства с разными айдишниками, но одинаковым значением. Или я чего то не понимаю. К примеру если мне нужно использовать один размер для маржина и радиуса, то какой нужно написать id?

2024-07-09 19:05 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            .add(R.id.mainContainer, CategoriesListFragment())
Да, переделал.

2024-07-10 08:37 UTC, ievetrovdev approved these changes

2024-07-10 08:48 UTC, merged