RA-23 transferring logic from a fragment to a viewmodel
vvaganov/RecipeApp pull request #20
Opened 2024-09-14 17:38 UTC by vvaganov

2024-09-15 10:52 UTC, ievetrovdev requested changes

2024-09-15 10:52 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        viewModel.recipeState.observe(viewLifecycleOwner) { it ->
лучше не оставлять it, а давать более осмысленные названия, по типу state

2024-09-15 10:52 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                    viewModel.onFavoritesClicked(recipeId)
Внутри observer лучше ссылать только на данные слушателя, чтобы не возникло непонятного стейта, где  recipeId будет отличаться от того, что в стейте.

2024-09-15 10:52 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +    private var recipeId: Int? = null
Хорошим тоном будет сразу в recipeId присвоить значение из аргументов. При корректной работе фрагмента должен существовать id, иначе мы попадем в непонятный стейт. Можно сразу перхватывать эту ситуацию через ?:throw IlligalArgumentException

2024-09-15 10:52 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val recipe = STUB.getRecipeById(recipeId)
Сейчас происходит работа с данными в ui, нарушается принцип архитектуры MVVM. Чтоб этого избежать,  инициализацию адаптеров лучше тоже перенести в observer

2024-09-15 10:54 UTC, ievetrovdev commented
Также теперь есть баг, в Избранном везде открывается классический бургер. Это связанно с тем, что мы до сих пор кладем Recipe, а не Id

2024-09-18 03:20 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +    private var recipeId: Int? = null
Иван, чет я затупил! Наверное как обычно не правильно понимаю задачу. Что значит сразу присвоить значение из аргументов? Ведь аргументы появятся только в onViewCraeted. Я понял, что нужно быть уверенным что recipeId будет не нулом, но как?:)

2024-09-18 03:26 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +                    viewModel.onFavoritesClicked(recipeId)
Понял

2024-09-18 03:28 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        viewModel.recipeState.observe(viewLifecycleOwner) { it ->
Принято

2024-09-18 03:29 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val recipe = STUB.getRecipeById(recipeId)
Я так понимаю, что не только инициализацию адаптеров нужно переносить. У нас еще seekBar обновляется. Его наверное в следующих задачах делать будем?

2024-09-18 03:34 UTC, vvaganov commented
Вроде как сейчас избранное работает корректно. У меня вообще крашилось при переходе на избранное, почистил кэш приложения. Все заработало. Рецепты добавляются те, которые выбраны!

2024-09-19 11:20 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +    private var recipeId: Int? = null
Аргументы фрагмента доступные уже в onCreate, когда происходит начальная инициализация фрагмента. В  onViewCreated, как следует из названия, создаются сами вьюхи (изображение экрана). В этот момент фрагмент уже существует и проинициализирован. 
Я же хотел предложить такую запись, через кастомный get(),  без лишней инициализации переменной. А c помощью через элвис-оператор `?:` выбрасывать ошибку при нулевом значении.
private val recipeId: Int
        get() = arguments?.getInt(ARG_RECIPE_ID) ?: throw IllegalArgumentException("...")

2024-09-19 11:23 UTC, ievetrovdev commented
> Вроде как сейчас избранное работает корректно. У меня вообще крашилось при переходе на избранное, почистил кэш приложения. Все заработало. Рецепты добавляются те, которые выбраны!

Да, при работе с sharedPreferences, полезно будет очистить хранилище приложения. При тесте может попасть непонятное значение в память, из-за этого может возникнуть непредвиденный стейт.

2024-09-19 11:38 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val recipe = STUB.getRecipeById(recipeId)
Да, сикбар тоже нарушает MVVM сейчас, но с ним мы будем работать позже в другом задании

2024-09-19 11:40 UTC, ievetrovdev approved these changes
Молодец! Весь функционал корректно работает. Ответил на комменты. Остальное - некретичное, давай в следующем пр поправим

2024-09-19 14:59 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +    private var recipeId: Int? = null
Да уж. Искал, искал как можно иннициализировать, но все что находил, это то что аргументы можно инициализировать в онвьюкрейт. Хотя и были сомнения.
Ладно, ща буду точно знать.
Один вопрос, наверное больше к знанию коллина относится, но все таки, чем отличается запись через геттер от просто инициализации?
т.е. private val recipeId: Int = arguments?.getInt(ARG_RECIPE_ID). В этом случае инициализации не происходит, и значение так и остется null?

2024-09-20 06:13 UTC, merged