RA-24 getting drawable from assets was put into the viewmodel
vvaganov/RecipeApp pull request #21
Opened 2024-09-20 06:54 UTC by vvaganov

Чет я не понял насчет возвращать  null. У меня в стейте по умолчанию draweble null, и если вдруг с загрузкой изображения что то пошло не так, то мы отдаем исключение и не обновляем стейт или не так работает?

2024-09-20 09:35 UTC, ievetrovdev commented
![image](https://github.com/user-attachments/assets/e2879cb4-3e06-41c8-a244-965ca327c716)
Отвечу на прошлый коммент здесь.
Все присвоения, которые мы делаем в классе вне функций, автоматически вызываются в блоке init{}. Просто для удобства эта конструкция опущена. Вот так выглядит инициализация переменных на самом деле.
```
class Example {
    val a: Int
    val b: Int
    init {
        a = 10
        b = a * 2
    }
}
```
Аргументы мы сможем получить только в методе onCreate(), а init{} стартует сразу,  поэтому мы и получаем null.

А кастомный геттер get() будет срабатывать каждый раз, когда обратились к переменной. То есть в самой переменной ничего не лежит, она просто переадресует на это значение. Очень сильно похоже на by lazy, только не сохраняет значение.
Проще всего будет понять на примере с временем. 
```
class Example{
    val currentTimeA = Clock.systemUTC().millis() //  Всегда Будет возвращать единственное время, момент создания класса
    
    val currentTimeB: Long
        get() = Clock.systemUTC().millis() // Каждый раз будет выводить актуальное время системы
 }
 ```

2024-09-20 18:15 UTC, ievetrovdev commented
setRecipeUi лучше убрать. Приватные функции служат в основном для того, чтоб сократить повторяемость кода, а этот метод является одной строчкой кода, почему бы сразу не обращаться к этой строчке напрямую

2024-09-20 18:25 UTC, ievetrovdev commented
> Чет я не понял насчет возвращать null. У меня в стейте по умолчанию draweble null, и если вдруг с загрузкой изображения что то пошло не так, то мы отдаем исключение и не обновляем стейт или не так работает?

Сейчас, если выбросится исключение, код в блоке try не будет выполнен, отработает catch. При некорректной загрузки стейт останется без изменений, по хорошему нужно бы присвоить null внутри catch блока для drawable в стейте

2024-09-20 18:26 UTC, ievetrovdev requested changes

2024-09-20 18:26 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
>              setRecipeUi(_recipeState.value?.copy(recipe = recipe, isFavorites = false))
Это условие лишние, можно просто напрямую передавать isFavorite в  state

2024-09-20 18:26 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        }
Хорошим тоном будет в едином месте, как правило в конце метода,  менять весь стейт сразу, а не частями в разных строчках.

2024-09-21 06:38 UTC, vvaganov commented
Чет я запутался как тут комменты работают!

Ладно. Чуть порефакторил я метод onFavoritesClicked, исходя из полученных знаний:). И вроде все работает корректно, но заметил один баг!!! При нажатии на иконку isFavorites, что добавляя в избранное, что убирая из него. Ломается разметка. Как будь то бы в ресайклерВью у каждого элемента с низу увеличивается паддинг. И это в обоих списках, как в ингредиентах так и в методе.
Сперва думал что глюк эмулятора. Но нет, на физическом девайсе та же история. 
Вообщем откатился я до предыдущей версии. И понял, что баг этот появился после переноса инициализации адаптеров в observer.
Пытался отследить где это происходит, через дебаг. Но видимо мой уровень знаний пока не достаточен для решения данной проблемы. Почему то мне кажется что, что то в адаптерах происходит. Но как это связано с isfavorites, я не понимаю:(.

2024-09-21 19:09 UTC, ievetrovdev commented
> Чет я запутался как тут комменты работают!
> 
> Ладно. Чуть порефакторил я метод onFavoritesClicked, исходя из полученных знаний:). И вроде все работает корректно, но заметил один баг!!! При нажатии на иконку isFavorites, что добавляя в избранное, что убирая из него. Ломается разметка. Как будь то бы в ресайклерВью у каждого элемента с низу увеличивается паддинг. И это в обоих списках, как в ингредиентах так и в методе. Сперва думал что глюк эмулятора. Но нет, на физическом девайсе та же история. В общем откатился я до предыдущей версии. И понял, что баг этот появился после переноса инициализации адаптеров в observer. Пытался отследить где это происходит, через дебаг. Но видимо мой уровень знаний пока не достаточен для решения данной проблемы. Порылся еще и понял, что это из за divider. Тупо удалил его. Нет разделителся нет проблемы:))) .Видимо с каждым обновлением стейта, раз вызывается initRecycle, divider что то добавляет. Не могу пока решить:(

Да, при каждом изменении стейта добавляется новый divider для ресайклеров. Предлагаю вынести создание девайдера в отдельный метод setDevider и делать его в initUi, не внутри observer

2024-09-21 19:09 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +            _recipeState.value = _recipeState.value?.copy(recipeImage = null)
лучше тогда присваивать не стейту null,  а переменной drawable. Либо ничего не далать, тк стандартное значение у drawable null

2024-09-22 09:03 UTC, ievetrovdev approved these changes
Молодец! Всё верно сделал

2024-09-23 03:04 UTC, merged