RA-25 moved the seekBar to initUI
vvaganov/RecipeApp pull request #22
Opened 2024-09-23 05:22 UTC by vvaganov

2024-09-25 06:11 UTC, ievetrovdev commented
> viewModel.recipeState.observe(viewLifecycleOwner) { state -> val recipe = state.recipe val customAdapterIngredient = IngredientsAdapter(recipe?.ingredients) val customAdapterMethod = MethodAdapter(recipe?.method) customAdapterIngredient.updateIngredients(state.numberServings) customAdapterIngredient.notifyDataSetChanged() Иван, у меня вопрос этот notifyDataSetChanged() вообще здесь ну или где то еще, в нашем случае вообще нужен? Без него точно также все меняется. Мне кажется он нужен только если список объектов изменился. В нашем случае список не меняется. Или я не правильно думаю?
> 
> Код добавления паддинга для listIngedient глаза мозолил, вынес в отдельную функцию. По хорошему наверное и seekBar можно получить в отдельной функции
> 
> Еще не доходит как работает эта строчка private val viewModel: RecipeViewModel by activityViewModels() Читал про делегаты, если by lazy я понял, то с этим не доходит.

Сейчас при изменении стейта в наблюдателе адаптеры каждый раз создаются заново (там, где прописан класс адаптера со скобками основного конструктора). Поэтому создается впечатление, что данные обновляются внутри адаптера. 

После этапа рефакторинга notifyDataSetChanged() будет актуален, когда мы только будем передавать новые данные в dataSet и этим методом будем просить адаптер перерисовать список. Иначе визуально он не будет изменяться. 

А почему сейчас решил использовать notifyDataSetChanged()? Напиши в лс

2024-09-25 06:22 UTC, ievetrovdev commented
> Еще не доходит как работает эта строчка
> private val viewModel: RecipeViewModel by activityViewModels()
> Читал про делегаты, если by lazy я понял, то с этим не доходит.

ага. by lazy это отложенная инициализация. только в момент обращения к переменной.
делегат by activityViewModels() используется для получения экземпляра ViewModel, связанного с Activity. Он позволяет нескольким фрагментам в одной Activity иметь доступ к одному и тому же экземпляру ViewModel. 

Это как общая библиотека для всех фрагментов внутри одной Активити. 

Предлагаю использовать делегат by viewModels(). Так как нам нужна инициализация вью модели в пределах фрагмента, а не общая для всех фрагментов вью модель. То есть переиспользуемые данные на разных фрагментах здесь не нужны 

by viewModels() используется для создания и получения ViewModel, который будет привязан к текущему фрагменту или активити. Это значит, что каждый фрагмент или активити, использующий этот делегат, будет иметь собственный экземпляр ViewModel.

2024-09-25 06:30 UTC, ievetrovdev requested changes
И не забывай использовать автоформатирование. В том числе и для удаления неиспользуемых импортов.

2024-09-25 06:30 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeState.value = _recipeState.value?.copy(numberServings = progress)
Копируем значение обычно из публичных неизменяемых переменных

2024-09-25 06:30 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>                  }
на каждом обновлении стейта переустанавливаешь наблюдатель. можно избежать этой операции

2024-09-25 06:30 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          seekBar.setOnSeekBarChangeListener(
можно будет вынести опять же на этапе рефакторинга чуть позже

2024-09-25 11:55 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>                  }
Ну только такое решение на ум приходит пока

2024-09-25 13:39 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        _recipeState.value = _recipeState.value?.copy(numberServings = progress)
А в чем разница? Я думал, что публичная переменная в основном для  обращений из вне.

2024-09-25 13:40 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          seekBar.setOnSeekBarChangeListener(
вынесем:)

2024-09-26 16:52 UTC, ievetrovdev approved these changes
Всё корректно, молодец!

2024-09-27 08:45 UTC, merged