RA-26 create class PortionSeekBarListener, initializing adapters outs…
vvaganov/RecipeApp pull request #23
Opened 2024-09-28 08:49 UTC by vvaganov

…ide the observer

Итоги решения данной задачи:
Я наконец то осознал что такое коллбек:)
Начал понимать, что такое лямбда функция
Наконец то пригодилась функция notifyDataSetChanged() :)

Все работает, но! мне кажется что вроде как инициализация рецепта стала медленее что ли, чисто визуально. При нажатии на рецепт, какая то пауза. Такая же пауза при изменении значения seekBar а. Что то мне подсказывает что дело в ресайклерах.
Еще момент, обновления в обсервере dataset - ов. Пока я не понимаю, для чего это?

2024-09-28 21:11 UTC, ievetrovdev commented
> Все работает, но! мне кажется что вроде как инициализация рецепта стала медленее что ли, чисто визуально. При нажатии на рецепт, какая то пауза. Такая же пауза при изменении значения seekBar а. Что то мне подсказывает что дело в ресайклерах. Хотя, возможно мне просто кажется так. Может эмулятор тупит. Еще момент, обновления в обсервере dataset - ов. Пока я не понимаю, для чего это?

Возможно эта пауза связана с тем, что я отписал в коменте. Твои списки отрисовываются дважды при нажатии на рецет. Глянь после исправления коммента, останется ли она?
С SeekBar вроде все корректно.

Через dataSet мы объявляем наш текущий список и в observer мы через эти строки инициируем его первый вид. Для полной оптимизации можно это делать только с условием dataSet.isEmpty, чтобы это происходило только при первом разе, когда список пустой. 
Почему эту работает довольно трудный момент для осознания. Первый observer срабатывает сразу, он идёт как продолжение initUI функции, а у нас все методы синхронные, поэтому в этот момент еще происходит инициализация адаптера и данные применяются корректно. Во всех остальных случаях пришлось бы вызывать notifyDataSetChanged, чтобы адаптер понял когда надо перерисовывать список.

2024-09-28 21:11 UTC, ievetrovdev requested changes

2024-09-28 21:11 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val seekBar: SeekBar = recipeBinding.sbNumberOfServings
Такой подход с созданием отдельной переменной не особо приветствуется, мы для этого и внедряли binding, чтоб создались все переменные для каждой view. Если нужно улучшить читаемость, то лучше просто это сделать через with(recipeBinding.sbNumberOfServings)

2024-09-28 21:11 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val customAdapterIngredient = IngredientsAdapter(STUB.getRecipe().flatMap { it.ingredients })
Сейчас ты обращаешься к имитации сервера напрямую в ui, хотя мы должны это делать во viewModel. Давай в initUI просто передавать пустые списки.Лишь потом в observer, когда данные загрузятся, они отобразятся

2024-09-28 21:11 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
>          seekBar.setPadding(resources.getDimensionPixelSize(R.dimen.indent_0))
Давай перенесем эту строку в xml файл, чтоб на макете были видны эти padding. Однако seekBar немного специфичен, придется для каждой из сторон прописать отдельно его. paddingTop = "0dp" и тд. У него не реализованы параметры других padding

2024-09-29 08:45 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val customAdapterIngredient = IngredientsAdapter(STUB.getRecipe().flatMap { it.ingredients })
Все, я понял, ни каких данных во фрагменте мы не получаем:), все через ViewModel. С двойной отрисовкой тоже понятно. Все заработало быстрее

2024-09-29 08:49 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +        val seekBar: SeekBar = recipeBinding.sbNumberOfServings
соглачен, так красивее, ну и менее затратно конечно. Я стараюсь понять где возможжно обойтись без создания доп переменных. Но пока конечно не всегда получается. Но буду стараться!

2024-09-29 18:39 UTC, ievetrovdev approved these changes
Всё верно! Молодец!

2024-09-30 10:19 UTC, merged