RA-27 create RecipeRepository and ViewModel for all fragments
vvaganov/RecipeApp pull request #24
Opened 2024-10-02 08:52 UTC by vvaganov

Иван, привет!
Статью почитал, что мог осилить, постарался применить. В частности, я так понимаю, что однонаправленный поток данных это: Репозиторий(где мы получаем данные и можем произвести над ними какие то действия)  -> ViewModel(где на основании этих данных формируется стейт) -> Фрагмент(где эти данные отображаются пользователю).

Вроде все сделал и все работает как и было. НО.
Не нужно ли было SharePreferences вынести в отдельный репозиторий? Вроде как сущность то одна, рецепты, а источники разнsе!
Контекст, смущает то что я из каждой Вью модели закидываю контекст для репозитория. Наверное в репозитории можно как то по другому получить его? Пытался искать, чет не знаю как вопрос задать в гугл. Выдает все для активити и фрагмента. Пока реализовал так.
Еще смущает инициализация STUB в конструкторе репозитория, не знаю почему, но как то кажется не правильно это что ли.
Ну вобщем пока так. Статью еще буду читать, много не знакомых слов там есть, думаю со временем станет все более ясным!

2024-10-02 17:28 UTC, ievetrovdev commented
> Иван, привет! Статью почитал, что мог осилить, постарался применить. В частности, я так понимаю, что однонаправленный поток данных это: Репозиторий(где мы получаем данные и можем произвести над ними какие то действия) -> ViewModel(где на основании этих данных формируется стейт) -> Фрагмент(где эти данные отображаются пользователю).

В целом так, но это больше замкнутый круг. Пользователь через взаимодействие с ui вызывает метод ВьюМодели, ВьюМодель запрашивает данные у репозитория. Репозиторий возвращает актуальные данные, ВьюМодель меняет стейт, триггирится observer, ui меняется.

2024-10-02 17:30 UTC, ievetrovdev commented
> Вроде все сделал и все работает как и было. НО. Не нужно ли было SharePreferences вынести в отдельный репозиторий? Вроде как сущность то одна, рецепты, а источники разнsе! Контекст, смущает то что я из каждой Вью модели закидываю контекст для репозитория. Наверное в репозитории можно как то по другому получить его? Пытался искать, чет не знаю как вопрос задать в гугл. Выдает все для активити и фрагмента. Пока реализовал так. Еще смущает инициализация STUB в конструкторе репозитория, не знаю почему, но как то кажется не правильно это что ли. Ну вобщем пока так. Статью еще буду читать, много не знакомых слов там есть, думаю со временем станет все более ясным!

Лучше вынести работу с SharedPreferences как отдельный DataSource и передавать этот dataSource в конструктор класса Repository. Repository должен только обращаться к источником данных и преобразовывать их. Репозиторий не должен работать с контекстом вообще, но в DataSource это допускается. Есть отдельная статья про data слой, там подробнее описано про источники данных
![image](https://github.com/user-attachments/assets/6bbf17d7-1aac-4018-8381-1508620d1054)
https://developer.android.com/topic/architecture/data-layer?hl=ru

Правильно, что ты передаешь DataSource STUB через конструктор, просто это заглушка, к которой можно обращаться напрямую. Но так намного сложнее будет переписать, когда появится в качестве источника данных настоящий сервер. В текущей реализации намного проще будет перейти

2024-10-02 18:19 UTC, ievetrovdev requested changes

2024-10-02 18:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/Constants.kt
>  const val PREF_FILE_NAME = "preferencesFavoritesId"
Вроде бы я писал, про то что нужно прописывать константы в конкретном object Constants.  
Когда ты пишешь const val просто за пределами класса, оно становится глобальной переменной, но это уже будет не часть класса, а часть всего модуля. Нарушается инкапсуляция.
Все константы должны быть прописаны внутри companion object класса, а не за его пределами

2024-10-02 18:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +    fun getFavorites(): MutableSet<String> {
Вынести работу с sharedPref в отдельный dataSource

2024-10-02 18:19 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +private const val MESSAGE_EMPTY_FAVORITE_LIST = "Вы еще не добавили ни одного рецепта в избранное"
Это сообщение нужно брать из ресурсов. Эта логика больше связана с ui,  её бы вынести во фрагмент, а в observer просто проверять на favoritesSet.isEmpty()

2024-10-03 05:09 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +private const val MESSAGE_EMPTY_FAVORITE_LIST = "Вы еще не добавили ни одного рецепта в избранное"
Эксперементирую:). Понял, вернул как было!

2024-10-03 05:50 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/Constants.kt
>  const val PREF_FILE_NAME = "preferencesFavoritesId"
Честно скажу, я не помню, говорили мы про companion obgects или нет. Мог конечно пропустить мимо ушей.

Чет я на счет этих двух констант сомневаюсь, они используются в каждом фрагменте. Их либо здесь оставлять, либо прописывать компаньон объект в каждом.

2024-10-03 07:58 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +    fun getFavorites(): MutableSet<String> {
вынес. Подумал и для фаворит создал еще и репозиторий свой. Потому как фавориты нужны только в двух вьюмоделях. И чтобы не передавать лишнюю зависимость например в листкатогорий и листрецептов, создал отдельный оепо. Наверное можно было как то по другому реализовать.

2024-10-03 09:07 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +    fun getFavorites(): MutableSet<String> {
Иван, это вообще нормально передавать контекст через конструктор?

2024-10-03 11:12 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +    fun getFavorites(): MutableSet<String> {
Context это god-object, он может делать много разных вещей. В твоем случае лучше передавать не весь контекст, а только нужную его часть для работы - SharedPreferencies

2024-10-03 11:23 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/Constants.kt
>  const val PREF_FILE_NAME = "preferencesFavoritesId"
Немного неправильно ты меня понял)  Держать в файле Constants можно, но оно должно быть обёрнуто в каком-нибудь классе, например 
object Constants{
const val ARG_CATEGORY_ID = "ARG_CATEGORY_ID"
}

2024-10-03 12:25 UTC, ievetrovdev requested changes

2024-10-03 12:25 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        return favoritesRepository.getRecipeData().toList().contains(recipeId.toString())
Это можно вынести на уровень репозитория

2024-10-03 12:25 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/FavoritesLocalDataSources.kt
> +        val sharedPref: SharedPreferences =
Префы должны объявляться один раз, а потом обращаться к ним. Каждый раз искать их по ключу - лишняя трата ресурсов.
Как я писал вышел, если передашь перфы в конструктор,  то и эта проблема уйдёт

2024-10-03 14:49 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +    fun getFavorites(): MutableSet<String> {
Я понял как это работает:)

2024-10-03 14:49 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
> +        return favoritesRepository.getRecipeData().toList().contains(recipeId.toString())
Да, нужно время что бы научиться понимать что к ui а что к data.
Вынес в репозиторий

2024-10-03 14:50 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/FavoritesLocalDataSources.kt
> +        val sharedPref: SharedPreferences =
Сделал. Действительно все оказывается очень просто:)

2024-10-03 14:53 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/Constants.kt
>  const val PREF_FILE_NAME = "preferencesFavoritesId"
Ааа, понял, я почитал сперва companion а не constants. Скорее всего не было до этого разговора про это:)
Только я не понял разницы. Ведь кто угодно может получить доступ к этому объекту

2024-10-03 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/Constants.kt
>  const val PREF_FILE_NAME = "preferencesFavoritesId"
При подходе без класса обёртки, все эти константы станут top-level и при наборе текста в любом классе она будет вылазить в подсказках. Если таких констант будет 1000, они займут всё место и быстрым импортом будет пользоваться не удобно
<img width="571" alt="Снимок экрана 2024-10-03 в 21 48 24" src="https://github.com/user-attachments/assets/3d9915e5-c249-4959-b138-d79ac784b1d1">

Когда же оно внутри объекта, мы должны сначала импортировать объект, чтобы увидеть его константы

2024-10-03 19:06 UTC, ievetrovdev approved these changes
Молодец, по заданию всё верно сделал. Оставил несколько косметических замечаний, поправь в следующем ПР. На комменты ответил

2024-10-03 19:06 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/FavoritesRepository.kt
> +        return getRecipeData().toList().contains(recipeId.toString())
Лучше, чтоб методы не зависили друг о друга внутри. Вдруг придется переделывать getRecipeData, тогда и поменяется работа этой функции. Правильнее будет дёргать DataSource напрямую и видоизменять данные из него

2024-10-03 19:06 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/data/FavoritesLocalDataSources.kt
> +        val mutableSteId = HashSet<String>(setId)
небольшая опечатка

2024-10-03 19:06 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +    )
Здесь что-то страшное со скобками происходит, сделать автоформатирование)

2024-10-04 01:45 UTC, merged

2024-10-04 01:47 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/FavoritesLocalDataSources.kt
> +        val mutableSteId = HashSet<String>(setId)
поправил

2024-10-04 04:44 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/FavoritesRepository.kt
> +        return getRecipeData().toList().contains(recipeId.toString())
Принял, поправил

2024-10-04 04:44 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +    )
Но, чет:) Лишние скобки были