RA-28 navigation via NavController is implemented
vvaganov/RecipeApp pull request #25
Opened 2024-10-06 08:44 UTC by vvaganov

Вобщем сделал пока так! Все работает!
Надо еще по разбираться как это под капотом работает.

2024-10-06 19:23 UTC, ievetrovdev requested changes

2024-10-06 19:23 UTC, ievetrovdev commented on app/src/main/res/navigation/nav_graph.xml
> +            android:id="@+id/action_categoriesListFragment_to_recipesListFragment3"
Что-то с неймингом action не так, лишние цифры в конце, давай приведем их к нормальному виду

2024-10-06 19:23 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListFragment.kt
> +        findNavController().navigate(R.id.recipesListFragment, bundle)
Стрелочки между фрагментами на nav_graph мы не просто так делали, после этого сгенерировался action, который напрямую делает переход к фрагменту. Эти экшены можно настраивать для своих целей. Давай везде будем использовать их, вместо прямого вызова конкретного фрагмента.

2024-10-06 19:23 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            findNavController(R.id.my_nav_host_fragment).navigate(R.id.categoriesListFragment)
В MainActivity использовать action не получится.
Но присутсвет проблемное поведение твоего приложения. Попробуй 10 раз подряд нажать на кнопку Категорий, все они попадут в backstack, чтобы их все закрыть придется нажать 10 раз на кнопку назад. Для action можно прописать параметр app:launchSingleTop="true", так он будет открываться лишь единожды, но для фрагментов из MainActivity это не сработает, поскольку они без action.Придется сделать по другому, создать navOptions и прописать эти настройки

2024-10-06 19:23 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            findNavController(R.id.my_nav_host_fragment).navigate(R.id.categoriesListFragment)
Пример реализации:
![image](https://github.com/user-attachments/assets/a3bc2f13-0d98-4606-9a70-ec9bc6d9589b)

2024-10-07 10:48 UTC, vvaganov commented on app/src/main/res/navigation/nav_graph.xml
> +            android:id="@+id/action_categoriesListFragment_to_recipesListFragment3"
чет ага, не понял почем так, автоматом же создавались. Я щас попробовал на новом проекте, та же история, студия подставляет какие то цифры в название

2024-10-07 10:49 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListFragment.kt
> +        findNavController().navigate(R.id.recipesListFragment, bundle)
все,  понял как это работает. Я я думаю, зачем эти стрелочки создавали если такое же обращение к фрагментам как и было:)
Мне почему то очень тяжело понимать документацию.

2024-10-07 10:54 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            findNavController(R.id.my_nav_host_fragment).navigate(R.id.categoriesListFragment)
сделал.
А вот такая вот реализация, когда элементы управления в активити, это нормально?. Почему кнопки во фрагментах не разместить? Или придется тогда в каждом фрагменте писать одни и те же кнопки наверное.

2024-10-07 11:28 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListFragment.kt
> +        findNavController().navigate(R.id.recipesListFragment, bundle)
Jetpack Navigation гораздо проще понять, глянув другие примеры реализации на нём или видеоролики на эту тему. Это набор инструментов для более легкой навигации, просто нужно понять как они работают, по тексту не так удобно

2024-10-07 12:04 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +            findNavController(R.id.my_nav_host_fragment).navigate(R.id.categoriesListFragment)
Навигация Activity находится на уровень выше фрагментов, для неё нужен свой способ взаимодействия.
В Jetpack Navigation есть своя нижняя навигация, но она не подходит по дизайну и не входит в этот курс
https://developer.android.com/guide/navigation/integrations/ui?hl=ru

2024-10-07 12:05 UTC, ievetrovdev approved these changes
Всё коррекнто! Молодец!

2024-10-07 14:47 UTC, merged