RA-05 A fragment for Favorites has been created, onClick methods for …
vvaganov/RecipeApp pull request #3
Opened 2024-07-10 09:51 UTC by vvaganov

…buttons have been implemented

2024-07-10 18:50 UTC, ievetrovdev requested changes

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/bwFavourites"
а что значит bw? обычно сокращенно пишут btn для кнопки или целиком button

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                    replace<CategoriesListFragment>(R.id.mainContainer)
Почти хорошо, за исключением того, что фрагмент с категориями надо открывать сразу при старте приложения

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +    private val favoriteFragmentBinding get() = _favoriteFragmentBinding!!
!! – оператор-утверждение "это не null" . Как я упоминал ранее – это опасный оператор и не рекомендуется его использовать, тк если в переменную все же придет null – приложение крашнется.

Это отрицательно повлияет на пользовательский опыт и сразу без дебага будет сложно найти причину вылета приложения. Устройств на андройд (и версий андройд) множество, далеко не все работают идеально, как наши собственные или эмулятор. Поэтому, чтобы меньше было проблем в будущем, подкладываем солому заранее. А именно добавляя разные безопасные обработчики.

Здесь же предлагаю применить более элегантный вариант с помощью делегата lazy, который использует ленивую инициализацию. Это такой механизм, который в лямбде принимает в нашем случае inflate() и возвращает созданный объект, который будет создан при первом обращении к нему.

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +        _favoriteFragmentBinding = FragmentFavoritesBinding.inflate(inflater,container,false)
Не применено автоформатирование (рекомендую прожимать автоформат после окончания работы над файлом или перед коммитом)

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +        return view
Почему бы не сократить строку, написав без дополнительной переменной: return binding.root

2024-07-10 18:50 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Обычно строки выносятся для локализаци и их переиспользования. Тексты-заглушки не стоит выносить, а достаточно добавить в tools, например. Они не будут использоваться в продакшен коде, их не должен видеть пользовать. Локализовать их тоже не потребуется.

2024-07-10 19:24 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/MainActivity.kt
> +                    replace<CategoriesListFragment>(R.id.mainContainer)
Да, я сперва так и сделал, но потом подумал, а что я повешаю на кнопку тогда? Решил, что наверное изначально будет загружаться какой то другой фрагмент:)
А так если я загружу этот фрагмент при запуске, то на кнопу нужно прописыват этот же ког? 
Ну вобщем тут я не допонял:(

2024-07-10 19:32 UTC, vvaganov commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
добавилась автоматически, не обратил внимания, удалил

2024-07-10 19:40 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +        _favoriteFragmentBinding = FragmentFavoritesBinding.inflate(inflater,container,false)
Да, конечно. Если в intellij я это уже почти на автомате, то тут еще привыкаю. Ососенно в xml файлах забываю делать:)

2024-07-11 06:38 UTC, vvaganov commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/bwFavourites"
изменил, пересмотрел видео урок:)

2024-07-11 06:47 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/FavoritesFragment.kt
> +    private val favoriteFragmentBinding get() = _favoriteFragmentBinding!!
Почитал, посмотрел, исправил. Я так понял здесь мы обходимся без каких либо проверок на null, потому что, если такого лайаута не существует, то приложение и не c компилируются вообще?

2024-07-11 12:11 UTC, ievetrovdev approved these changes

2024-07-11 12:11 UTC, ievetrovdev commented on app/src/main/java/com/example/recipeapp/CategoriesListFragment.kt
> +            layoutInflater
Хорошо, это еще можно в одну строку поместить, чтобы покрасивее было.

2024-07-11 12:14 UTC, merged