RA-35 getting data from the server using retrofit
vvaganov/RecipeApp pull request #31
Opened 2024-10-17 11:52 UTC by vvaganov

Иван привет!
Переписать все методы в в репозитории, оказалось совсем не сложно. Правда с ламбдами пришлось немного повозиться, в силу своей не опытности в этом вопросе. Но все таки реализовал коллбек. Пытался его сделать при помощи интерфейсов и классов, и вроде бы все получилось, но как то все не красиво, решил оставить лямбду.

Дальше начались трудности которые я решить не смог.
1. Я не понимаю зачем мы делаем отдельный тред, если основной все равно приходится тормозить чтоб дождаться загрузки. Хотя я понимаю, что в основном потоке андроид не даст сделать запрос. Как то наверное, после получения данных, состояние как то должно обновиться и отобразиться. Сейчас же, если я уберу метод get() у потока и не дождусь пока данные загрузятся,  на экранах ни чего нет. Может я callback как то не правильно реализовал:(
2. Не смог решить как создавать путь recipes.androidsprint.ru/api/recipes?ids=0%2C1%2C2%2C3%2C4, у меня получается ttps://recipes.androidsprint.ru/api/recipes?ids=0&ids=1&ids=2&ids=3
Что соответственно приводит к багу, выводится только первый элемент на экран.
В документации и по поиску примеров не нашел. Что то я там не до понимаю видимо что написано!

По поводу сложности использования тредов в репозитории. Я не могу оценить на сколько это сложно, так как опыта использования тредов в других местах у меня нету. Если сравнивать с тем что было в видео уроке, дак я разницы не заметил особой.

2024-10-18 16:11 UTC, Churickoid commented
> 2. Не смог решить как создавать путь recipes.androidsprint.ru/api/recipes?ids=0%2C1%2C2%2C3%2C4, у меня получается ttps://recipes.androidsprint.ru/api/recipes?ids=0&ids=1&ids=2&ids=3
>    Что соответственно приводит к багу, выводится только первый элемент на экран.
>    В документации и по поиску примеров не нашел. Что то я там не до понимаю видимо что написано!
В документации API описано какой тип надо отправлять и в каком формате. Нужно преобразовать список интов в строку, через запятую
![image](https://github.com/user-attachments/assets/0539084a-f3d2-4312-bee8-a7cdce474a27)

2024-10-18 16:30 UTC, Churickoid commented
> 1. Я не понимаю зачем мы делаем отдельный тред, если основной все равно приходится тормозить чтоб дождаться загрузки. Хотя я понимаю, что в основном потоке андроид не даст сделать запрос. Как то наверное, после получения данных, состояние как то должно обновиться и отобразиться. Сейчас же, если я уберу метод get() у потока и не дождусь пока данные загрузятся,  на экранах ни чего нет. Может я callback как то не правильно реализовал:(

Эта проблема вытекает из неправильной реализации асинхронной работы. Мы не должны вызывать get(), это как раз и блокирует главный поток. Всё оставшуюся логику мы долнжы перенести в лямдбу callback, чтобы она отработала не в главном потоке. Поскольку LiveData будет изменяться не из главного потока, чтоб не возникло проблем, внутри лямбды нужно менять значения через postValue

2024-10-18 16:35 UTC, Churickoid commented
После того как перепишешь логику без .get(), на уровне ui(фрагментов) нужно добавить корректную обработку null стейта и вызова toast, это ожин из пунктов задания.

В случае получения null, показывать [Toast](https://developer.android.com/guide/topics/ui/notifiers/toasts) с текстом 'Ошибка получения данных'.

2024-10-18 16:37 UTC, Churickoid commented
> А да, еще. Метод getCategoryById в репозитории оставил не реализованным. Так как мы недавно переделали на получаение Категории во вьюмодель списка рецептов из фрагмента списка рецептов, который туда приходит из фрагмента списка категорий:). Запутанно как то. Переделать обратно, что бы получать из репозитория? А между фрагментами передавать только Id катогории?. Надо уже понять, как все таки более рационально то?

Ты его реализовал, просто нигде не используешь. Работу адаптера оставь такой же, эта ручка api должна дальше пригодиться по заданиям

2024-10-18 16:43 UTC, Churickoid requested changes

2024-10-18 16:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        }.get()
Во всех методах нужно избавиться от .get(), в другом комменте подробнее ответил

2024-10-18 16:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                val service: RecipeApiService = retrofit.create(RecipeApiService::class.java)
Сервис всегда одинаковый, правильнее будет его создавать лишь единожды, а лишь потом только обращаться к нему

2024-10-18 16:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        .baseUrl("https://recipes.androidsprint.ru/api/")
Давай вынесем это в константу, строку из contentType тоже

2024-10-18 16:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        .addConverterFactory(Json.asConverterFactory(contentType))
Здесь ты подключил какой-то кастомный конвертер, давай лучше использовать стандартный из retrofit2
import retrofit2.converter.kotlinx.serialization.asConverterFactory

2024-10-18 19:03 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                val service: RecipeApiService = retrofit.create(RecipeApiService::class.java)
Да, конечно, не обратил внимания. Но уже стараюсь хотя бы а уровне обычных переменных не повторяться. Но не всегда все замечаю:)

2024-10-18 19:09 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        .baseUrl("https://recipes.androidsprint.ru/api/")
У меня вопрос по константам. Мы вообще любые константы выносим в объект. Или есть какие то правила, что наименования например чего бы то нибыло в объект, а пути к примеру в другое место?

2024-10-20 07:22 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        .addConverterFactory(Json.asConverterFactory(contentType))
Но, не понятно откуда я его взял вообще:). Че увидел первое в интернете то и подставил

2024-10-20 07:22 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        }.get()
Сделано!

2024-10-20 13:21 UTC, vvaganov commented
Арсений, привет!
В общем во фрагменте Избранного я так и не смог реализовать нормально Тост. Да и мне кажется в других как то не правильно реализовано, хотя работает.
Мне кажется надо пока идет загрузка, нужно еще какое то состояние показывать, хотя бы конкретно в избранном.

2024-10-20 14:49 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        .baseUrl("https://recipes.androidsprint.ru/api/")
Есть анти-паттерн магические числа, когда в коде мы используем какое-то число. Другим программистам будет трудно понять почему мы  именно его здесь исользуем, надо вынести его в константу и пояснить в названии для каких целей используется. Анти-паттерны надо избегать.
Тоже самое можно и сказать для строк, почему в той или иной части кода используется какая-то строка. 
Нужно вынести в константу её и названием дать больше информации.

По сути нужно выносить все непонятные объекты любых типов. Может и можно догадаться, что это за ссылка в строке, но лучше расширить информацию о ней в названии констант
Но нули и пустые строки например выносить не надо,  конкретики как правильно не нужно в таких случаях.

2024-10-20 15:39 UTC, Churickoid requested changes
Щас еще проблема - текст в шкапе на экранах рецептов с выключенным интернетом не отображается, хотя эти данные доступны вне зависимости от интернета. Надо вынести из под условия эту строку

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListFragment.kt
>          if (category != null) {
Условие всегда true

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListFragment.kt
> +        viewModel.getCategoryList().observe(viewLifecycleOwner) { categoryList ->
В целом реализация toast почти правильная, но ты следишь за изменением функции,  которая возвращает статичный liveData. Эта реализация станет рабочей, если ты будешь слушать categoryList.observe и в onViewCreated вызывать viewModel.loadCategoryList()

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/Constants.kt
> +    const val LOAD_ERROR = "Ошибка загрузки"
Это надо вынести в ресурсы, часть UI, должна имень несколько переводов

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +    private val categoryList: MutableLiveData<List<Category>?> = MutableLiveData(emptyList())
Лучше использовать один стейт CategoryListUiState, так будет легче расширить приложение, если понадобится новый функционал

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +    fun getCategoryList(): LiveData<List<Category>?> {
Такой подход все-таки больше джавосвкий. Лучше будет вынести в отдельную переменную, как было раньше, и прописать кастомный get() с loadCategoryList() и возвратом categoryList

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +            callback(listRecipe)
В избранном не отображается, потому что здесь не хватает try catch, как в других твоих местах. Щас этот поток падает без каких-либо знаков в logcat, такая специфика использования thread. 
При обработки ошибки всё будет работать корректно

2024-10-20 15:39 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
>          //TODO `load from network`
Уже тудушку можно убирать) Работает из  сети

2024-10-20 15:42 UTC, Churickoid commented
> Арсений, привет! В общем во фрагменте Избранного я так и не смог реализовать нормально Тост. Да и мне кажется в других как то не правильно реализовано, хотя работает. Мне кажется надо пока идет загрузка, нужно еще какое то состояние показывать, хотя бы конкретно в избранном.

Показывать опознавательные знаки загрузки - хорошая практика, но у нас приложение работает с малым объемом информации, очень быстрые операции даже с плохим интернетом, и задание не требует это.  То что пользователь может нажимать на кнопки навигации и тд, поскольку основной поток не заблокирован, уже достаточно

2024-10-21 15:29 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
>          //TODO `load from network`
Арсений, я так и не смог сообразить как реализовать Тост в РецептСтейте. Проблема в том что, по умолчанию в стейте recipe по умолчанию = Null. Соответственно, если я пишу условие проверки на нулл, ну он и выкидывает сразу при загрузке Тост. В листах там по умолчанию emptyList, а здесь recipe. Как то его инициализировать не Null надо или что то еще, не могу сообразить:(

2024-10-21 15:29 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +            callback(listRecipe)
Ага, чет пропустил.

2024-10-21 15:30 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +    fun getCategoryList(): LiveData<List<Category>?> {
Я вроде как понял, как это работает:) Беда в плохом понимании как вообще исполняется код. Но потихоньку начинает доходить:)

2024-10-21 20:32 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +        return favoritesState
Эта функция сейчас вообще лишняя, я в прошлых комментах предлагал всю эту функцию перенести внутрь кастомного getter:
 val favoritesState: LiveData<FavoritesUiState> get(){
loadFavoritesList()
return _favoritesState
}
И внутри фрагментом попдисываться именно на эту переменную. Вообще все функции get... можно заменять на котлиновскую переменную с кастомным геттером

2024-10-21 20:32 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesFragment.kt
> +                    customAdapter.notifyDataSetChanged()
Щас в списке Избранного не кликаются элементы, не хватает объявления listener'а в адаптере

2024-10-21 20:32 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
>          //TODO `load from network`
Вообще идеально будет переписать листенер адаптер из recipeList и сразу передавать recipe в RecipeFragment. Лишний раз ходить на сервер и грузить тоже самое смысла нет.
Можно также добавить отдельный параметр isError в стейт, но за ним надо следить, чтоб он после одного отрабатывания сразу отключался.
Как самое быстрое решение - просто прописывать dummy Recipe с дефолтными значениями, но это плохо скажется на пользовательском опыте.

Предлагаю делать через первый вариант

2024-10-22 07:43 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +        return favoritesState
А, я пробовал так сделать только без фнукции loadFavoritesList(). Проблема в том что если я пишу сразу в геттер запрос к базе, то при открытии фрагмента, идет постоянное обращение г БД. Соответственно Ui становится неадекватным.
Я пытался найти ответ, примеры реализации такого геттера, но к сожалению пока не нашел.

При той реализации которая была. Все работает.

2024-10-22 07:45 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeViewModel.kt
>          //TODO `load from network`
Переписал, все работает норм! Соответственно в RecipeFragment ни какой проверки на null нет, так как если не загрузится resepList, то и до рецепта дела не дойдет. А если уж лист прогрузился и вдруг вырубился интерне, то рецепт отобразится в любом случае!

2024-10-22 07:49 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/favorites/FavoritesViewModel.kt
> +        return favoritesState
Вероятней всего конечно, я  еще много чего не знаю про  LiveData и про слушатель!

2024-10-22 17:17 UTC, Churickoid approved these changes
Всё верно поправил, молодец! Единственное, в следующем ПР надо поправить бесконечное зацикливание  из-за геттера.
![image](https://github.com/user-attachments/assets/524683dc-e51c-4e49-8fa0-8ff2bd252512)
Если глянуть код реализации LiveData, в setValue вызывается dispatchingValue, где вызывается getValue. Сейчас такая ситуация, что при каждом изменении value вызывается кастомные геттер, который меняет value. 
Использовать функции внутри liveData, которые меняют liveData приводят к зацикливанию.
Предлагаю просто сделать loadFavoritesList публичным и вызывают её в initUi единожды, а из геттера убрать

2024-10-23 05:03 UTC, vvaganov commented
Все работает, но есть одна беда! Все с тем же фаворитлистом. При первой инициализации фрагмента, стейт берется по умолчанию, там список пустой и все норм. Дальше, если у нас в избранном что то ест, то все отлично, коллбек грузит список. Но если в избранное ни чего не добавлено,  когда возвращается колбек из базы, то прилетает null. Ну и соответственно вылетает Тост. Хотя проблема не в загрузке, а всего лишь нет ни чего в избранном.
Я ни как не могу реализовать проверку, что бы этого не происходило, только как я не пробовал, не получается. 
Нужно что бы база возвращала не Null  если в избранном нет ни чего, а тот же пустой список, если это возможно конечно.
Ну либо как то проверку по другому строить. До меня не доходит:)

2024-10-23 19:46 UTC, Churickoid requested changes

2024-10-23 19:46 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                callback(listRecipe)
Просто здесь добавь механизм  listRecipe ?: emptyList =) Ошибок не возникло, значит передаем пустой список

2024-10-23 19:46 UTC, aGroupoid approved these changes
Апрувлю, поправь эту мелкую проблему уже в следующем задании

2024-10-24 05:28 UTC, merged