RA-36 uploading images using the glade library
vvaganov/RecipeApp pull request #32
Opened 2024-10-24 09:33 UTC by vvaganov

Как то слишком все просто получилось:). Есть подозрение что не совсем эффективно!

2024-10-24 18:58 UTC, danelyan requested changes
> Как то слишком все просто получилось:). Есть подозрение что не совсем эффективно!

В этом как раз таки и преимущество использования библиотек )

2024-10-24 18:58 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListAdapter.kt
>              } catch (e: Exception) {
try..catch вокруг уже не нужен, в случае ошибки будет просто рисоваться R.drawable.img_error

2024-10-24 18:58 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/recipes/listRecipes/RecipeListAdapter.kt
>              } catch (e: Exception) {
try catch не нужен

2024-10-24 18:58 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +            recipeBinding.imgRecipe.setImageResource(R.drawable.img_error)
try/catch не нужен

2024-10-25 03:14 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/recipe/RecipeFragment.kt
> +            recipeBinding.imgRecipe.setImageResource(R.drawable.img_error)
Исправлено

2024-10-25 03:14 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/listRecipes/RecipeListAdapter.kt
>              } catch (e: Exception) {
Исправлено

2024-10-25 03:14 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoriesListAdapter.kt
>              } catch (e: Exception) {
Ну да, точно, чет я не подумал, исправлено!

2024-10-25 19:34 UTC, Churickoid approved these changes
Молодец! Всё верно!

2024-10-26 05:43 UTC, merged