RA-37 added coroutines to database queries
vvaganov/RecipeApp pull request #33
Opened 2024-10-26 07:01 UTC by vvaganov

Сделал. Почитал про корутины. Я так понимаю можно избавиться от колбеков!

2024-10-26 14:20 UTC, Churickoid commented
> Сделал. Почитал про корутины. Я так понимаю можно избавиться от колбеков!

Да, это был основной их минус. Мы не могли возвращать значения из этих функций, приходилось внедрять коллбеки. Корутины могуть делать асинхронный return, о колбеках можно забыть)

2024-10-26 14:23 UTC, Churickoid requested changes
Нужно выпилить коллбеки из всех методов Repository, возвращать переменные через return@. Надо пользоваться благами корутин,  их основное приемущество, что мы можем работать с несколькими suspend функциями внутри скоупов как с обычными функциями,  без внедрения лишних паттернов

2024-10-27 05:05 UTC, vvaganov commented
В документации к корутинам, приведен пример, когда проверка на ошибки на уровне репозитория делается во вью модели. Я оставил проверку в репозитории. Не знаю правильно это или нет, но все работает, и кода вроде как меньше.

2024-10-27 18:42 UTC, Churickoid approved these changes
Всё верно, молодец! В комментах ответил на вопрос и дал рекомендацию

2024-10-27 18:42 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +        return withContext(Dispatchers.IO) {
Так работает, но предлагаю использовать более чистую конструкции  suspend fun 
```
getRecipeListByCategoryId(categoryId: Int): List<Recipe>? = withContext(Dispatchers.IO) {}
```

2024-10-27 18:42 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                null
Такой способ возвращения значения верный. withContext в конструктор принимает лямбда-функцию, просто в котлин последний параметр, если это лямбда можно опустить и вынести за аргументы. Вернуть значение в лямбдах по синтаксису можно так, более длинный способ return@withContext value. В документации котлин по лямбда-функциям и функциям высшего порядка написаного про это

2024-10-28 04:21 UTC, merged