RA-39 create cash Category in room dataBase
vvaganov/RecipeApp pull request #35
Opened 2024-10-29 09:04 UTC by vvaganov

Смущает передача aplication из вью модели в репозиторий. Да и в самой модели, я так понимаю принимать контекст в конструктор не совсем хорошо.
Создал функцию changeState() для обновления стейта после загрузки с бекенда и обновления бд. Пока другого способа как обновить стейт, я не нашел.

2024-10-29 20:43 UTC, danelyan requested changes
Хорошо. Есть небольшое примечание

2024-10-29 20:43 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +class CategoryListViewModel(private val application: Application) : AndroidViewModel(application) {
> Смущает передача aplication из вью модели в репозиторий. Да и в самой модели, я так понимаю принимать контекст в конструктор не совсем хорошо.

Пока что это нормально. Ведь мы не сам создаем CategoryListViewModel(), ее создает встроенная фабрика. В будущем сделаем лучше

2024-10-29 20:43 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +    private fun changeState() {
1. Слишком обобщенное название метода. Можно назвать например `loadCategoriesFromCache()`
2. Можно убрать `viewModelScope.launch` и сделать метод suspend, а в `loadCategoryList` переместить его внутрь `viewModelScope.launch { ... }`

2024-10-29 20:43 UTC, danelyan commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +                changeState()
тут ты делаешь отрисовку для **каждого** элемента коллекции категорий.
Можно так:
```Kotlin
    loadCategoriesFromCache()
    repository.getCategoryList()
        ?.forEach { category ->
            repository.insertHashCategory(category)
        }
    loadCategoriesFromCache()
```

То есть - сначала загрузить их кеша, чтобы как можно быстрее отобразить данные (актуально при плохом интернете). Потом сделать запрос в сеть, загрузить записи и сохранить последовательно в кеш. И лишь после этого вновь загрузить данные из кеша. Можно кстати еще добавить сравнение куда-нибудь для новых и старых данных

2024-10-30 02:45 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/categories/CategoryListViewModel.kt
> +    private fun changeState() {
Чет затупил я. у меня же была именнно эта функция в начале. Потом с обновлением взял переименовал:)

2024-10-30 04:34 UTC, danelyan approved these changes
Отлично!

2024-10-30 05:35 UTC, merged