RA-40 create hash for Recipe, and IngredientConverter, MethodConverter
vvaganov/RecipeApp pull request #36
Opened 2024-10-30 08:09 UTC by vvaganov

Итак, повозился с конвертерами. Честно скажу, писал не сам, нашел в яндексе. Пока не очень понимаю как это работает, особенно в Ingredient. Но по разбираюсь. MethodConverter понять проще. Думаю возможно как то это все вообще в один конвертер завернуть, будут только меняться типы которые cодержит List. Но пока решил так оставить. Хотя, переделаю наверное.
Далее миграции. Пошел самым простым путем fallbackToDestructiveMigration(). Понимаю что это значит. Каждый раз база пересоздается с потерей всех данных. Конечно же, так делать не надо:). Есть куча примеров как создавать миграции нормально, но все на джаве пока нахожу. Тяжело понимать. Может подскажете где примеры, где есть на котлин.

2024-10-30 19:06 UTC, Churickoid commented
Нету возможности настроить универсальную миграцию. База данных продумывается заранее, если нужны доработки бдшки, раскатанной на пользователей, то для конкретного случая реализовывается свой механизм.
В данном слайе использовать fallbackToDestructiveMigration() самый адекватный способ при такой разработке. Таблица будет очищаться только после апдейта версии, мы же её не даём пользователям, для учебного проекта самый подходящий вариант. 
Сейчас о миграции думать не надо, это нужно в тех случаях, когда есть пользователи, чтоб не затерся их кэш

2024-10-30 19:13 UTC, Churickoid commented
Кэширование не реализовано до конца. Список рецептов должен грузится сначала из кэша. Если кэш пустой, то идём на сервер и заполняем локальную бд. Нужно будет реализовать механизм, чтобы рецепты из кэша грузились по конкретному id категории. Чтобы делать такие запросы, предлагаю расширить сущность Recipe отдельной переменной categoryId и при заполнении в БД устанавливать это значение через .copy(). Затем по этому параметру делать запросы

2024-10-31 06:17 UTC, vvaganov commented
Не то что бы не до конца, а вообще не реализовано:). Это я затупил. Я код то написал, Хотя все равно не правильно, как оказалось. Но я накосячил с ветками и при смене ветке видимо код не сохранился. Я еще не очень хорошо гит знаю, было какое то предупреждение, но я его не понял. Вобщем как то так.
Все реализовал. Сперва сделал что то не правильно, и сохранение в базе было не правильным, из за чего все затупило. Пришлось создать новую базу. Вроде все работает корректно!

2024-11-01 20:43 UTC, Churickoid requested changes

2024-11-01 20:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/ui/recipes/listRecipes/RecipeListViewModel.kt
> +    private suspend fun fromHashRecipeList(categoryId: Int) {
Хэш и Кэш достаточно разные понятия, их путать не надо) В данном случае мы работаем с Кэшем

2024-11-01 20:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                db.recipeDao().getAllRecipe(categoryId)
Каждый раз создавать новый экземпляр Dao не оченть то и хорошая практика, лишние затраты. Давай их создавать единожды при создании репозитория либо лениво через by lazy

2024-11-01 20:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/data/Converter.kt
> +    }
В котлине можно работать со строками намного проще. Делает тоже самое, но гораздо проще

```
class MethodConverter {
@TypeConverter
fun fromMethod(method: List<String?>): String = method.joinToString(",")

@TypeConverter
fun toMethod(data: String): List<String> = data.split(",")
}
```

2024-11-01 20:43 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/model/Recipe.kt
> +    @PrimaryKey() val id: Int,
скобки лишние

2024-11-02 04:24 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/ui/recipes/listRecipes/RecipeListViewModel.kt
> +    private suspend fun fromHashRecipeList(categoryId: Int) {
так то да, чет не обратил внимания

2024-11-02 04:24 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/RecipeRepository.kt
> +                db.recipeDao().getAllRecipe(categoryId)
Исправил

2024-11-02 04:25 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/data/Converter.kt
> +    }
Действительно проще. Исправил

2024-11-02 04:25 UTC, merged