RA-45 implemented Hilt
vvaganov/RecipeApp pull request #39
Opened 2024-11-04 17:42 UTC by vvaganov

Ну вроде бы все:)

2024-11-04 18:30 UTC, Churickoid requested changes
Еще надо поправить небольшие замечания =) Тогда точно всё.

Остались еще пустые фабрики, их бы тоже почистить

2024-11-04 18:30 UTC, Churickoid commented on gradle/libs.versions.toml
> +hiltAndroid = "2.51.1"
две одинаковые переменные, уже есть hilt, давай везде испоьзоват её

2024-11-04 18:30 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    annotation class IoDispatcher
То что создал свою аннотацию для диспатчера - сильно! Хволю

2024-11-04 18:30 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    fun provideDataBase(@ApplicationContext context: Context): AppDatabase = Room.databaseBuilder(
Почитай еще про аннотацию @Singleton. Если сейчас Database заинджектится куда-то в другое место, создастся новый объект, может произойти рассинхрон между данными. Добавь эту аннотацию, где уместно

2024-11-05 04:42 UTC, vvaganov commented on gradle/libs.versions.toml
> +hiltAndroid = "2.51.1"
Исправлено

2024-11-05 07:34 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    fun provideDataBase(@ApplicationContext context: Context): AppDatabase = Room.databaseBuilder(
Почитал, понял, Добавил. Я сперва думал, что аннотация SingletonComponnent применяется ко всем вложенным элементам. Как оказалось это не так. Ну хоть по разбирался что это вообще значит.

2024-11-05 07:48 UTC, vvaganov commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    annotation class IoDispatcher
А у меня по другому и не получилось, я пытался сперва вообще без аннотации, но без нее не определяется. А какой то стандартной аннотации для CoroutineContext я пока не обнаружил:)

2024-11-05 09:29 UTC, Churickoid commented on app/src/main/java/com/example/recipeapp/di/RecipeModule.kt
> +    annotation class IoDispatcher
Можно без аннотации, по умолчанию прописать dispatcher = Dispatcher.Io и не заполнять это поле в хилте. Твой подход более надежный

2024-11-05 09:51 UTC, Churickoid commented
Всё верно! В последнем коммите ты исправил bags - мешки) Мы всё-таки исправляем bugs
Поздравляю с завершением курса!

2024-11-05 09:51 UTC, Churickoid approved these changes

2024-12-06 10:00 UTC, merged