Ra 07 implement the basic layout of the screen with a list of categories
vvaganov/RecipeApp pull request #5
Opened 2024-07-12 12:33 UTC by vvaganov

2024-07-13 20:02 UTC, ievetrovdev requested changes

2024-07-13 20:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +        <ImageView
Давай заполним данные тестовыми данными любой категории. Это можно сделать через атрибут tools. Наша задача сейчас понять, как это примерно выглядит на превью в студии.

2024-07-13 20:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            />
Не забывай применять автоформатирование. В том числе и в разметках. Когда все атрибуты стоят на своих местах (в порядковом смысле) - со временем привыкаешь и быстро ориентируешься при их считывании.

2024-07-13 20:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +                style="@style/StyleTitle14"
Давай заполним данные тестовыми данными любой категории. Через атрибут tools. Передача отладочных данных в атрибут text может грозить тем, что их увидит пользователь. Изображение тоже - любое в качестве заглушки для превью.

2024-07-13 20:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_width="156dp"
Лейаут для элемента списка следует заполнять полностью по всей ширине. То есть это верстка не для части экрана, а текущий лейаут – полноценный элемент списка. В самом списке ресайклера после отрисовки элемент примет уже соответствующую адаптивную форму в зависимости от параметров отображения.

2024-07-13 20:02 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="220dp"
Предлагаю во всем этой разметке задавать только высоту изображения, а все остальные элементы высоты в разметке будут адаптивными (по размеру контента)

Все остальные значения в лейауте следует сделать адаптивными. Ширину по родителю, а высота будет по размеру контента, тк описания могут приходить разной длины.

2024-07-13 20:34 UTC, vvaganov commented on app/src/main/res/layout/item_category.xml
> +            />
Но, опять забыл, стараюсь

2024-07-13 20:35 UTC, vvaganov commented on app/src/main/res/layout/item_category.xml
> +    android:layout_width="156dp"
Поянл, исправли

2024-07-13 20:41 UTC, vvaganov commented on app/src/main/res/layout/item_category.xml
> +        <ImageView
сделано

2024-07-15 13:14 UTC, ievetrovdev approved these changes
Обращаю внимание на стиль именования пулл реквеста. RA-07 ...

2024-07-15 13:35 UTC, merged