RA-11 implemented the output of recipes by clicking on a category
vvaganov/RecipeApp pull request #9
Opened 2024-07-19 15:58 UTC by vvaganov

2024-07-20 18:28 UTC, ievetrovdev requested changes

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/assets/bcg_recipes_list.png
Картинки выгрузил не исходные, а из экрана – закругленные уже. Закруглять углы будем программно) В макете нужные изображения хранятся в секции с компонентами.

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            tools:ignore="MissingConstraints"
MissingConstraints говорит о том, что ты принудительно игнорируешь позиционирование элемента. Но зачем игнорировать, когда можно задать родителей по всем осям и быть спокойным за положение элемента.

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            />
форматирование

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_height="224dp">
ресурсы

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/layout/item_recipe.xml
> +            android:layout_height="130dp"
аналогичные проблемы

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="recipeListTitle">#5F3678</color>
Это не заголовок, а цвет. Постфикс для цветов всегда устанавливается Color

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
>      <style name="StyleTitle14.StyleTitle20">
Указывай родителей принудительно, как это требовалось в первых этапах

2024-07-20 18:28 UTC, ievetrovdev commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <TextView
Если текст будет слишком большой, то может располагаться вплотную к правой границе или вовсе вылезет за пределы экрана. Так как мы находимся внутри констрейнта, есть пара хитрых атрибутов, чтобы это реализовать более элегантно. Не забудь добавить констрейнт справа и все протестировать
app:layout_constrainedWidth="true"
app:layout_constraintHorizontal_bias="0.0"

2024-07-20 20:02 UTC, vvaganov commented on app/src/main/res/layout/item_recipe.xml
> +            android:layout_height="130dp"
исправлено

2024-07-20 20:02 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        android:layout_height="224dp">
исправлено

2024-07-21 08:26 UTC, vvaganov commented on app/src/main/assets/bcg_recipes_list.png
сделал

2024-07-21 08:26 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipes_list.xml
> +            tools:ignore="MissingConstraints"
исправлено

2024-07-21 08:28 UTC, vvaganov commented on app/src/main/res/values/colors.xml
> +    <color name="recipeListTitle">#5F3678</color>
Понял

2024-07-21 08:28 UTC, vvaganov commented on app/src/main/res/values/styles.xml
>      <style name="StyleTitle14.StyleTitle20">
исправлено

2024-07-21 08:46 UTC, vvaganov commented on app/src/main/res/layout/fragment_recipes_list.xml
> +        <TextView
Если я конечно все правильно понял, то сделал

2024-07-22 05:34 UTC, ievetrovdev approved these changes

2024-07-22 05:37 UTC, merged